# Copyright (C) 2010-2016 The CyanogenMod Project
# Copyright (C) 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/X705F/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/X705F/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/lenovo/X705F/proprietary/etc/firmware/A96T316_fw.bin:system/etc/firmware/A96T316_fw.bin \
    vendor/lenovo/X705F/proprietary/etc/firmware/LTE_A96T316_fw.bin:system/etc/firmware/LTE_A96T316_fw.bin \
    vendor/lenovo/X705F/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/lenovo/X705F/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/lenovo/X705F/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/lenovo/X705F/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/lenovo/X705F/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/lenovo/X705F/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/lenovo/X705F/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/lenovo/X705F/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/lenovo/X705F/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/lenovo/X705F/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/lenovo/X705F/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/lenovo/X705F/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/lenovo/X705F/proprietary/lib/extractors/libmmparser.so:system/lib/extractors/libmmparser.so \
    vendor/lenovo/X705F/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/lenovo/X705F/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/lenovo/X705F/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/lenovo/X705F/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/lenovo/X705F/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/lenovo/X705F/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/lenovo/X705F/proprietary/lib/libsd_sdk_display.so:system/lib/libsd_sdk_display.so \
    vendor/lenovo/X705F/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/lenovo/X705F/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/lenovo/X705F/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/lenovo/X705F/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/lenovo/X705F/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/lenovo/X705F/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/lenovo/X705F/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/lenovo/X705F/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/lenovo/X705F/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/lenovo/X705F/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/lenovo/X705F/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/lenovo/X705F/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/lenovo/X705F/proprietary/lib64/libsd_sdk_display.so:system/lib64/libsd_sdk_display.so \
    vendor/lenovo/X705F/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/lenovo/X705F/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.qti.gnss@1.1.so:system/lib64/vendor.qti.gnss@1.1.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.qti.gnss@1.2.so:system/lib64/vendor.qti.gnss@1.2.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.qti.gnss@2.0.so:system/lib64/vendor.qti.gnss@2.0.so \
    vendor/lenovo/X705F/proprietary/lib64/vendor.qti.gnss@2.1.so:system/lib64/vendor.qti.gnss@2.1.so

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0 \
    CNEService \
    com.qualcomm.location \
    dpmserviceapp
